"""empty message

Revision ID: 34d1f0ce8eb8
Revises: 47f8b7321a48
Create Date: 2023-11-01 15:53:55.267173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d1f0ce8eb8'
down_revision = '47f8b7321a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_index('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.create_index('phone_number', ['phone_number'], unique=False)

    # ### end Alembic commands ###
