"""empty message

Revision ID: 47f8b7321a48
Revises: 
Create Date: 2023-11-01 15:43:03.780837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47f8b7321a48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_name', sa.String(length=25), nullable=True),
    sa.Column('patient_email', sa.String(length=200), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('doctor_name', sa.String(length=25), nullable=True),
    sa.Column('health_issue', sa.String(length=100), nullable=True),
    sa.Column('appointment_datetime', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Completed'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('password', sa.String(length=1000), nullable=False),
    sa.Column('profile_description', sa.Text(), nullable=True),
    sa.Column('speciality', sa.String(length=20), nullable=False),
    sa.Column('contact', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('password', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('patient_name'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('prescription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_name', sa.Integer(), nullable=False),
    sa.Column('doctor_name', sa.Integer(), nullable=False),
    sa.Column('date_prescribed', sa.DateTime(), nullable=False),
    sa.Column('medication_name', sa.String(length=100), nullable=False),
    sa.Column('dosage_instructions', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_name'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['patient_name'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prescription')
    op.drop_table('patient')
    op.drop_table('doctor')
    op.drop_table('appointment')
    # ### end Alembic commands ###
